services:
  - type: web
    name: version-aware-doc-assistant
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .

    healthCheckPath: /health
    autoDeploy: true

    envVars:
      - key: PORT
        value: "8000"

      - key: OPENAI_API_KEY
        sync: false

      - key: OPENAI_MODEL
        value: gpt-5.6-luna

      - key: QDRANT_URL
        sync: false

      - key: QDRANT_API_KEY
        sync: false

      - key: QDRANT_COLLECTION_NAME
        value: documentation

      - key: LANGSMITH_TRACING
        value: "true"

      - key: LANGSMITH_API_KEY
        sync: false

      - key: LANGSMITH_PROJECT
        value: version-aware-doc-assistant
